<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.6" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.1.7" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CarExplorer.Application\CarExplorer.Application.csproj" />
    <ProjectReference Include="..\CarExplorer.Infrastructure\CarExplorer.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Configurations\" />
    <Folder Include="Extensions\" />
    <Folder Include="Middlewares\" />
  </ItemGroup>

</Project>
